version: '3'

services:
  react:
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./chat_web_client
    ports:
      - 3000:3000
  node:
    build:
      dockerfile: Dockerfile
      context: ./chat_server
    ports:
      - 4000:4000
      - 4002:4002